verb1=input("verb")
verb2=input("verb")
verb3=input("verb")
verb4=input("verb")
verb5=input("verb")

noun1=input("noun")
noun2=input("noun")
noun3=input("noun")
noun4=input("noun")
noun5=input("noun")
noun6=input("noun")
noun7=input("noun")
noun8=input("noun")

adjective1=input("adjective")
adjective2=input("adjective")
adjective3=input("adjective")
adjective4=input("adjective")
adjective5=input("adjective")

print("In a", adjective1, " town, where", noun1, verb1, " endlessly, There arises a",  noun2," so ", adjective2," and ", noun3," , It's time to ", verb2," with ", adjective3, noun4," and", verb3," with ", adjective4, noun5,". Are you ready to", verb4," the",  noun6," and", verb5," like never before? Embrace the", adjective5, noun7", and let's", verb6," together, my", noun8")